name: calcium_imaging_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pip
  # Data handling
  - numpy>=1.21
  - pandas>=1.3
  - h5py>=3.4
  # Learning
  - scikit-learn>=1.0
  # Plotting and visualization
  - matplotlib>=3.4
  - tqdm>=4.62
  - pip:
    - tables>=3.6 # requiremnt for saving and loading pandas.DataFrame
    # Models
    - pyMou@git+https://github.com/mb-BCA/pyMOU.git@master
