rule_conf:
  entry:
    {}
  parcellation:
    {}
  prefilters:
    {}
  conditions:
    {}
  feature_calculation:
    {}
  decoder:
    {}

branch_opts:
  mouses:
    - GN06
  dates:
    - 2021-01-20_10-15-16
  parcellations:
    - anatomical
    - SVD
    - ICA
  filters:
    - All
  conditions:
    #null
    default:
      phase:      stimulus
      modalities: vistact
    left_vistact:
      sides:      left
    right_vistact:
      sides:      right

  features:
    mean:
      max_components : [64]
    covariance:
      max_components : [64]
    moup:
      timelags: [3]
      max_components : [64]
    #autocovariance:
      #timelags: [[0],[1]]
      #max_components : 65
  decoders:
    default:
      reps: [5]
    MLR:
    1NN:
    LDA:
    RF:
  rfe:
    selected_features_n:
      - full
      - 20
      - 50
      - 100

parcellation_opts:
  paths:
    anatomical: resources/meta/anatomical.mat


#Alternative manual conditions should be supported, currently having only left and right with unique modalities not possible e.g.
# something like (or with strings and we put a corresponding dict in utils to resolve the actual values)
# conditions:
#   condition1:
#     target_side_left:0
#     modality: 1
#   condition2:
#     target_side_left:1
#     modality: 0

trial_conditions:
  sides:
    column: target_side_left
    conds:
      left:   0
      right:  1
  modalities:
    column: modality
    conds:
      visual:   0
      tactile:  1
      vistact:  2

phase_conditions:
  pretrial:
    start:  15
    stop:   30
  stimulus:
    start:  30
    stop:   75

different_config_inputs: 1
