rule_conf:
  entry:
    {}
  parcellation:
    {}
  prefilters:
    {}
  conditions:
    {}
  feature_calculation:
    base_start : 15
    stim_start : 30
    stim_stop : 75
    max_components : 65
  decoder:
    {}

branch_opts:
  mouses:
    - GN06
  dates:
    - 2021-01-20_10-15-16
  parcellations:
    - anatomical
    - SVD
  filters:
    - All

parcellation_opts:
  paths:
    anatomical: resources/meta/areaMasks.mat

#Alternative manual conditions should be supported, currently having only left and right with unique modalities not possible e.g.
# something like (or with strings and we put a corresponding dict in utils to resolve the actual values)
# conditions:
#   condition1:
#     target_side_left:0
#     modality: 1
#   condition2:
#     target_side_left:1
#     modality: 0

conditional_opts:
  sides:
    - left
    - right
  modalities:
    - visual
    - tactile
    - vistact

features:
  - mean
  - covariance

selected_features_n:
  - full
  - 20
  - 50

#rfe_opts:

  #node_feats:
  #  -mean
  #n_nodes:  #Reduced Number of Components (Mean, Time Series,...)
  #  -20
  #interaction_feats:
  #  -covariance
  #n_interactions:  #Reduced Number of Edges between Components (Cov,Cor,Moup,...)
  #  -50



decode_opts:
  k_folds: 5
  decoders:
    - MLR
    - 1NN
    - LDA
    - RF

different_config_inputs: 1
