branch_opts:
  combine_sessions: False

  # Defines subjects and dates to use from Simons Experiment
  subjects:
      mSM65:
        - 08-Sep-2018

  # Defines conditions for Simon Experimental Setup
  conditions:
    default:
      phase: all
    left_visual:
      sides: left
      modalities: visual
    right_visual:
      sides: right
      modalities: visual
    left_auditory:
      sides: left
      modalities: auditory
    right_auditory:
      sides: right
      modalities: auditory
  

# Defines trial phases for Simon Experimental Setup
trial_conditions:
  sides:
    column: CorrectSide
    conds:
      left:   1
      right:  2
  modalities:
    column: StimType
    conds:
      visual:   1
      auditory: 2
  responses:
    column: ResponseSide
    conds:
      left: 1
      right: 2

phase_conditions:
  pretrial:
    start:  15
    stop:   90
  stimulus:
    start:  90
    stop:   141
  all:
    start: 15
    stop: 201
